apps/models/command.py
# -*- encoding: utf-8 -*-
import enum

from apps import db


class CommandType(enum.Enum):
    nmap = 'Nmap'
    nikto = 'Nikto'


class CommandModel(db.Model):
    __tablename__ = 'Command'

    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.Enum(CommandType))
    command = db.Column(db.String(255))
    description = db.Column(db.String(255))

    def __init__(self, **args):
        for key, value in args.items():

            if hasattr(value, '__iter__') and not isinstance(value, str):
                value = value[0]

            setattr(self, key, value)

    def __repr__(self):
        return str(self.target)

    @staticmethod
    def in_type(value):
        if value in ','.join(map(str, CommandType)):
            return True
        return False

apps/models/scan.py
# -*- encoding: utf-8 -*-

from apps import db
import datetime


class ScanModel(db.Model):
    __tablename__ = 'Scan'

    id = db.Column(db.Integer, primary_key=True)
    target = db.Column(db.Integer, db.ForeignKey("Target.id"), nullable=False)
    date_create = db.Column(db.DateTime(), default=datetime.datetime.now)
    date_update = db.Column(db.DateTime(), onupdate=datetime.datetime.now)
    status = db.Column(db.Enum('pending', 'processing', 'completed'))
    command = db.Column(db.Integer, db.ForeignKey("Command.id"), nullable=False)
    result = db.Column(db.LargeBinary)

    def __init__(self, **args):
        for key, value in args.items():

            if hasattr(value, '__iter__') and not isinstance(value, str):
                value = value[0]

            setattr(self, key, value)

    def __repr__(self):
        return str(self.target)

apps/models/target.py
# -*- encoding: utf-8 -*-
from typing import List

from apps import db


class TargetModel(db.Model):
    __tablename__ = 'Target'

    id = db.Column(db.Integer, primary_key=True)
    host = db.Column(db.String(255), unique=True)
    type = db.Column(db.Enum('ip', 'domain'))
    # scans = db.Relationship(List["Scan"])


    def __init__(self, **args):
        for key, value in args.items():

            if hasattr(value, '__iter__') and not isinstance(value, str):
                value = value[0]

            setattr(self, key, value)

    def __repr__(self):
        return str(self.target)

apps/default/forms.py
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired, EqualTo, Length


class UpdateAccountForm(FlaskForm):

    username = StringField('Username',
                           id='username',
                           validators=[DataRequired(), Length(min=5)])
    email = StringField('Email',
                        id='email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='password',
                             validators=[])
    passwordConfirm = PasswordField('Password confirm',
                                    id='password_confirm',
                                    validators=[EqualTo("password")])

apps/default/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint


blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/default/routes.py
# -*- encoding: utf-8 -*-
import json
from datetime import datetime

from time import sleep

from flask_login.utils import current_user
from sqlalchemy import desc

from apps.default import blueprint
from flask import render_template, request, redirect
from flask_login import login_required
from jinja2 import TemplateNotFound

from apps.default.forms import UpdateAccountForm
from apps.models import ScanModel, TargetModel, CommandModel, UserModel
from apps.tools import validate_ip, hash_pass
from apps import db, config

import validators
import threading

from apps.tools.thread import ThreadScanner


@blueprint.route('/index')
@login_required
def index():
    # from run import scan_event
    # scan_event('Event emitted from Python index')

    nb_targets = db.session.query(TargetModel.id).count()
    nb_commands = db.session.query(CommandModel.id).count()
    nb_scans = db.session.query(ScanModel.id).count()

    return render_template('default/index.html',
                           activepath='index',
                           nb_targets=nb_targets,
                           nb_commands=nb_commands,
                           nb_scans=nb_scans)


@blueprint.route('/targets', methods=['GET', 'POST'])
@login_required
def targets():
    if request.method == 'POST':
        if request.form['action'] == 'delete':
            id = request.form['id']
            if TargetModel.query.filter_by(id=id).first() is not None:
                target = TargetModel.query.filter_by(id=id).first()
                db.session.delete(target)
                db.session.commit()

        if request.form['action'] == 'add':
            targets_posted = request.form['targetsList']
            for host in targets_posted.splitlines():
                host = host.strip()
                if TargetModel.query.filter_by(host=host).first() is None:

                    # Add IP
                    if validate_ip(host):
                        target = TargetModel(host=host, type='ip')
                        db.session.add(target)
                        db.session.commit()

                    # Add Domain
                    if validators.domain(host):
                        target = TargetModel(host=host, type='domain')
                        db.session.add(target)
                        db.session.commit()

    return render_template('default/targets.html', activepath='targets', targets=TargetModel.query.all())


@blueprint.route('/scans', methods=['GET', 'POST'])
@login_required
def scans():

    if request.method == 'POST':
        if request.form['action'] == 'delete':
            id = request.form['id']
            if ScanModel.query.filter_by(id=id).first() is not None:
                scan = ScanModel.query.filter_by(id=id).first()
                db.session.delete(scan)
                db.session.commit()

        if request.form['action'] == 'add':
            scan = ScanModel(
                target=request.form['target'],
                command=request.form['command'],
                status='pending',
            )
            db.session.add(scan)
            db.session.commit()

    return render_template('default/scans.html',
                           activepath='scans',
                           scans=ScanModel.query.order_by(desc(ScanModel.date_update)).all(),
                           targets=TargetModel.query.all(),
                           commands=CommandModel.query.all())


@blueprint.route('/scans/detail/<scan_id>', methods=['GET', 'POST'])
@login_required
def scan_result(scan_id):
    scan = ScanModel.query.filter_by(id=scan_id).first()
    if scan is not None:
        target = TargetModel.query.filter_by(id=scan.target).first()
        command = CommandModel.query.filter_by(id=scan.command).first()
        result = json.loads(scan.result.decode("utf-8"))
        result_json = json.dumps(result, indent=4)
        return render_template('default/scan_result_nmap.html',
                               activepath='scans',
                               scan=scan,
                               target=target,
                               command=command,
                               result=result,
                               result_json=result_json)
    return redirect("/scans", code=200)


@blueprint.route('/commands', methods=['GET', 'POST'])
@login_required
def commands():
    if request.method == 'POST':
        if request.form['action'] == 'delete':
            id = request.form['id']
            if CommandModel.query.filter_by(id=id).first() is not None:
                command = CommandModel.query.filter_by(id=id).first()
                db.session.delete(command)
                db.session.commit()
        if request.form['action'] == 'add':
            if CommandModel.in_type(request.form['type']):
                command = CommandModel(
                    type=request.form['type'],
                    command=request.form['command'],
                    description=request.form['description'],
                )
                db.session.add(command)
                db.session.commit()

    return render_template('default/commands.html',
                           activepath='commands',
                           commands=CommandModel.query.all())


@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    success = None
    me = {
        'id': current_user.id,
        'email': current_user.email,
        'username': current_user.username
    }
    update_account_form = UpdateAccountForm(request.form)

    if request.method == 'POST' and update_account_form.validate():

        username = request.form['username']
        email = request.form['email']
        password = request.form['password']

        msg = None

        # Check username exists
        user = db.session.query(UserModel).filter_by(username=username).first()
        if user and user.id != me['id']:
            msg = 'Username already exists'

        # Check email exists
        user = db.session.query(UserModel).filter_by(email=email).first()
        if user and user.id != me['id']:
            msg = 'Email already exists'

        if msg is not None:
            return render_template('default/settings.html',
                                   msg=msg,
                                   user=me,
                                   form=update_account_form)
        else:
            user = db.session.query(UserModel).filter_by(id=current_user.id).first()
            user.username = username
            user.email = email
            if password:
                user.password = hash_pass(password)
            db.session.flush()
            db.session.commit()

            current_user.email = email
            current_user.username = username

            success = "Successfully saved"

            me = {
                'id': current_user.id,
                'email': current_user.email,
                'username': current_user.username
            }

    return render_template('default/settings.html',
                           success=success,
                           user=me,
                           form=update_account_form)


@blueprint.route('/scanner', methods=['GET', 'POST'])
@login_required
def scanner():
    print("Scanner lock: " + str(config.Config.SCANNER_LOCK))
    if request.method == 'POST':
        if request.form['action'] == 'start_thread':
            print("Start thread")
            thread_started = False
            for thread in threading.enumerate():
                if "thread_scanner" in thread.name:
                    thread_started = True

            if not thread_started:
                config.Config.SCANNER_LOCK = True
                my_thread = ThreadScanner(name="thread_scanner")
                my_thread.start()

        if request.form['action'] == 'stop_thread':
            print("Stop thread")
            for thread in threading.enumerate():
                if "thread_scanner" in thread.name:
                    config.Config.SCANNER_LOCK = False
                    sleep(3)

    print("=============== THREADS ===============")
    thread_started = False
    for thread in threading.enumerate():
        print(thread.name)
        if "thread_scanner" in thread.name:
            thread_started = True
    print("=============== THREADS ===============")

    return render_template('default/scanner.html', activepath='scanner', thread_started=thread_started)


@blueprint.route('/scanner/toast', methods=['GET'])
@login_required
def ajax_socket_message():
    message = 'Hello, world! This is a toast message.'
    return render_template('default/toast.html', message=message, now=datetime.now())

@blueprint.route('/<template>')
@login_required
def route_template(template):
    try:

        if not template.endswith('.html'):
            template += '.html'

        activepath = get_activepath(request)

        return render_template("default/" + template, activepath=activepath)

    except TemplateNotFound:
        return render_template('_errors/404.html'), 404

    except:
        return render_template('_errors/500.html'), 500


def get_activepath(request):
    try:
        activepath = request.path.split('/')[-1]
        if activepath == '':
            activepath = 'index'
        return activepath

    except:
        return None

apps/templates/default/commands.html
{% extends "_layouts/default.html" %}

{% block title %} Commands {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        <div class="modal fade" id="addCommandModal" tabindex="-1" role="dialog" aria-labelledby="Add a Command" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <form action="{{ url_for('home_blueprint.commands') }}" method="POST">
                        <input type="hidden" name="action" value="add">
                        <div class="modal-header">
                            <h5 class="modal-title" id="addCommandModalTitle">Add command</h5>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label class="custom-control-label" for="type">Type</label>
                                <select class="form-select" id="type" name="type" aria-label="Default select example">
                                    <option value="nmap">Nmap</option>
                                    <option value="nikto">Nikto</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="custom-control-label" for="command">Command</label>
                                <input class="form-control" name="command" id="command" type="text" />
                            </div>
                            <div class="form-group">
                                <label class="custom-control-label" for="description">Description</label>
                                <input class="form-control" name="description" id="description" type="text" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <div class="container-fluid px-4">
            <h1 class="mt-4"><i class="fas fa-terminal me-1"></i> Commands</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.index') }}">Home</a></li>
                <li class="breadcrumb-item active">Commands</li>
            </ol>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <div class="row justify-content-between">
                    <div class="col-4">
                    </div>
                    <div class="col-4 text-end">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addCommandModal">
                            <i class="fas fa-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th>Command</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th>Command</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {%- for command in commands %}
                            <tr>
                                <td>{{ command.id }}</td>
                                <td>{{ command.type.value }}</td>
                                <td>{{ command.command }}</td>
                                <td>{{ command.description }}</td>
                                <td>
                                    <form action="{{ url_for('home_blueprint.commands') }}" method="POST">
                                        <input type="hidden" name="action" value="delete">
                                        <input type="hidden" name="id" value="{{ command.id }}">
                                        <button type="button" class="btn btn-danger delete-btn" name="command {{ command.type.value }} {{ command.command }}"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </main>

{% endblock content %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
{% endblock javascripts %}

apps/templates/default/index.html
{% extends "_layouts/default.html" %}

{% block title %} Home {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Home</h1>
            <div class="row">
                <div class="col-xl-4 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="p-2 flex-fill">
                                    Targets: {{ nb_targets }}
                                </div>
                                <div class="p-2 flex-fill text-end fs-2">
                                    <i class="fas fa-network-wired"></i>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{ url_for('home_blueprint.targets') }}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="p-2 flex-fill">
                                    Commands: {{ nb_commands }}
                                </div>
                                <div class="p-2 flex-fill text-end fs-2">
                                    <i class="fas fa-terminal"></i>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{ url_for('home_blueprint.commands') }}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="p-2 flex-fill">
                                    Scans: {{ nb_scans }}
                                </div>
                                <div class="p-2 flex-fill text-end fs-2">
                                    <i class="fas fa-project-diagram"></i>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{ url_for('home_blueprint.scans') }}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

{% block javascripts %}
{% endblock javascripts %}

apps/templates/default/scanner.html
{% extends "_layouts/default.html" %}

{% block title %} Settings {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4"><i class="fas fa-crosshairs"></i> Scanner</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.index') }}">Home</a></li>
                <li class="breadcrumb-item active">Scanner</li>
            </ol>

            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h3 class="card-title">Thread scanner</h3>
                        </div>
                        <div class="card-body">
                            Status: {{'stopped' if not thread_started  else 'started'}}
                        </div>
                        <div class="card-footer">
                            <div class="d-flex">
                                <form class="p-2 flex-fill" method="post">
                                    <input type="hidden" name="action" value="start_thread">
                                    <button type="submit" class="{{'disabled' if thread_started }} btn btn-success">Start</button>
                                </form>
                                <form class="p-2 flex-fill text-end" method="post">
                                    <input type="hidden" name="action" value="stop_thread">
                                    <button type="submit" class="{{'disabled' if not thread_started }} btn btn-danger btn-stop">Stop</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>

{% endblock content %}

{% block javascripts %}
<script>
    $( document ).ready(function() {
        $('.btn-stop').on('click', function() {
            var $this = $(this);
            $this.append(' <i class="fas fa-spinner fa-spin"></i>')
        });
    });
</script>
{% endblock javascripts %}

apps/templates/default/scans.html
{% extends "_layouts/default.html" %}

{% block title %} Scans {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        <div class="modal fade" id="addScanModal" tabindex="-1" role="dialog" aria-labelledby="Add a Scan" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <form action="{{ url_for('home_blueprint.scans') }}" method="POST">
                        <input type="hidden" name="action" value="add">
                        <div class="modal-header">
                            <h5 class="modal-title" id="addScanModalTitle">Add scan</h5>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label class="custom-control-label" for="target">Target</label>
                                <select class="form-select" id="target" name="target" aria-label="Default select example">
                                    {%- for target in targets %}
                                        <option value="{{ target.id }}">{{ target.host }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="custom-control-label" for="command">Command</label>
                                <select class="form-select" id="command" name="command" aria-label="Default select example">
                                    {%- for command in commands %}
                                        <option value="{{ command.id }}">{{ command.description }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <div class="container-fluid px-4">
            <h1 class="mt-4"><i class="fas fa-project-diagram me-1"></i> Scans</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.index') }}">Home</a></li>
                <li class="breadcrumb-item active">Scans</li>
            </ol>
        </div>


        <div class="card mb-4">
            <div class="card-header">
                <div class="row justify-content-between">
                    <div class="col-4">
                    </div>
                    <div class="col-4 text-end">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addScanModal">
                            <i class="fas fa-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Target</th>
                            <th>Date created</th>
                            <th>Date updated</th>
                            <th>Status</th>
                            <th>Command</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Target</th>
                            <th>Date created</th>
                            <th>Date updated</th>
                            <th>Status</th>
                            <th>Command</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {%- for scan in scans %}
                            <tr>
                                <td>{{ scan.id }}</td>
                                <td>
                                    {%- for target in targets %}
                                        {% if scan.target == target.id %}
                                            {% if scan.status == "completed" %}
                                                <a href="{{ url_for('home_blueprint.scan_result', scan_id=scan.id) }}">{{ target.host }}</a>
                                            {% else %}
                                                {{ target.host }}
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{ scan.date_create }}</td>
                                <td>{{ scan.date_update }}</td>
                                <td>
                                    {% if scan.status == 'pending' %}<i class="fas fa-pause"></i> {% endif %}
                                    {% if scan.status == 'processing' %}<i class="fas fa-spinner fa-spin"></i> {% endif %}
                                    {% if scan.status == 'completed' %}<i class="fas fa-check-square"></i> {% endif %}
                                    {{ scan.status }}
                                </td>
                                <td>
                                    {%- for command in commands %}
                                        {% if scan.command == command.id %}
                                            {{ command.description }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    <form action="{{ url_for('home_blueprint.scans') }}" method="POST" class="inline-flex">
                                        <input type="hidden" name="action" value="delete">
                                        <input type="hidden" name="id" value="{{ scan.id }}">
                                        <button type="button" class="btn btn-danger delete-btn" name="scan"><i class="fas fa-trash"></i></button>
                                        {% if scan.status == "completed" %}
                                            <a href="{{ url_for('home_blueprint.scan_result', scan_id=scan.id) }}" class="btn btn-success"><i class="fas fa-eye"></i></a>
                                        {% endif %}
                                    </form>

                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </main>

{% endblock content %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
{% endblock javascripts %}